# Generated by Django 2.2.14 on 2020-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodtests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=10)),
                ('lower', models.FloatField(null=True)),
                ('upper', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bloodtests',
        ),
    ]
